### ISSUE TITLE
Websocket closing down on chat messages in 0.19

### ISSUE THREAD

**Issue by vin01** [revel/examples#41]
The issue seems to be arising from this commit: https://github.com/revel/revel/commit/cf64e7bf249c3c953bb25121cd714b5ad38907d3

The WebSocket connection closes down when a message is sent in the chat example using "Demonstration" mode as "WebSocket".

Error message in Google Chrome 62.0.3202.75:

`WebSocket is already in CLOSING or CLOSED state.`

**Comment by ptman** [comment]
https://github.com/revel/examples/blob/master/chat/app/views/WebSocket/Room.html#L68 should probably be JSON.stringify(message) if you use MessageReceiveJSON() to receive it https://github.com/revel/examples/blob/master/chat/app/controllers/websocket.go#L44

**Comment by ptman** [comment]
Chrome has a nice network debugger that can show the websocket frames sent and received

**Comment by simolev** [comment]
I second @ptman's comment and suggestion; `app/views/WebSocket/Room.html` line `68` should be: 
`    socket.send(JSON.stringify(message))`
instead of:
`    socket.send(message)`

This really turned me off since I just checked out revel, and went straight to the chat/websocket only to find out it doesn't work. Totally bad first impression you don't want newcomers to have. As mentioned, Google Chrome's developer tools make it really easy to pinpoint the issue, provided one knows a bare minumum of javascript and go.

Then I come here to open the issue and find out it has been **outstanding for more than four months** despite already having a suggested solution. The initial bad impression just got worse. Please **fix this as soon as possible** since examples are a new user's entry point and you want them to look good and make revel shine. Then, possibly, add more of them!

**Comment by notzippy** [comment]
Pull requests are always welcome and merged more rapidly. Focus has been on getting the main application to a v1 stable release See PR #43

**Comment by simolev** [comment]
@notzippy Great, thanx for the feedback!
